version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fDdiFw_KB2930otN
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  fastapi-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-gateway
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - mosquitto
    environment:
      DATABASE_URL: postgresql://postgres:fDdiFw_KB2930otN@postgres:5432/postgres
      REDIS_HOST: redis
      MQTT_HOST: mosquitto

volumes:
  pgdata: