services:
  postgres:
    image: postgres:15-alpine
    container_name: iot_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: iot_mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /var/www/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /var/www/mosquitto/data:/mosquitto/data
      - /var/www/mosquitto/log:/mosquitto/log
    restart: always

  fastapi-gateway:
    build:
      context: .
    container_name: iot_fastapi_gateway
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/postgres
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - TELEGRAM_BOT_TOKEN=8974351475:AAHTzxM7U_XvvUuwzhcFUdtDnpbuAyzcFcQ
      - API_SECRET_KEY=your-api-key
    depends_on:
      - postgres
      - mosquitto
    restart: always

  userbot:
    build:
      context: .
    container_name: iot_telegram_userbot
    command: python -m app.adapter_telegram_userbot
    volumes:
      - .:/app
      - ./userbot_session.session:/app/userbot_session.session
      - ./userbot_state.json:/app/userbot_state.json
    environment:
      - TELEGRAM_API_ID=34687255
      - TELEGRAM_API_HASH=0c8a94e104d60fe54bf05605122ae878
      - FASTAPI_USERBOT_URL=http://fastapi-gateway:8000/webhook/telegram-userbot
      - API_SECRET_KEY=your-api-key
    depends_on:
      - fastapi-gateway
    restart: always

volumes:
  pgdata:
